name: lint

on:
  push:
    branches:
      - "**"

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install cppcheck
      run: sudo apt install cppcheck

    - name: cppcheck
      run: cppcheck --enable=all --suppress=missingIncludeSystem --suppress=missingInclude --suppress=unmatchedSuppression --error-exitcode=1 src/

    - name: formatting
      run: find src -iname '*.h' -o -iname '*.cpp' -print0 | xargs -0 clang-format --dry-run --Werror
